name: Synchronization

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Synchronize to gitee
        uses: Yikun/hub-mirror-action@v1.1
        with:
          src: github/npuv5pp
          dst: gitee/lyfm
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          static_list: V5RPC
          
